[package]
name = "rustwebact"
version = "0.1.2"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Reactive Actor Web Apps for Rust on the Web"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/RustWebAct"
